# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPsP', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_incorporacion', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('consejo_regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.ConsejoRegional')),
            ],
        ),
    ]
